name: Deployment test
description: test
concurrency: prod

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy test
        run: |
          echo "success"
