name: Deployment

concurrency: production

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: |
        echo "success"
