name: Deployment

concurrency: prod

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: deploy
        run: |
          echo "success"
