name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    concurrency: prod
    steps:
      - name: deploy
        run: |
          echo "test"
