name: Deployment

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: prod
    concurrency: prod
    steps:
      - name: deploy
        run: |
          echo "test"
