name: Deployment

on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: stage
    concurrency: stage
    steps:
      - name: deploy
        run: |
          echo "test"
