name: Pull Request Checklist

on:
  pull_request:
    types:
      - opened
      - synchronize
  issue_comment:
    types:
      - created
      - edited

jobs:
  checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Read Pull Request Description
        id: pr-description
        run: |
          echo "$(cat ${{ github.event.pull_request.body_file }})" >> $GITHUB_ENV
          echo "description=$(cat ${{ github.event.pull_request.body_file }})" >> $GITHUB_ENV

      - name: Check Checklist
        run: |
          checklist=$(grep -oPz '(?s)(?<=## Checklist\n).*(?=\n##)' <<< "${{ env.description }}")

          # Check if "Added tests" is marked
          if echo "${checklist}" | grep -q "\[x\] added tests"; then
            echo "The 'Added tests' checkbox is marked."
            # Perform actions specific to "Added tests"
          else
            echo "The 'Added tests' checkbox is not marked."
            # Perform actions for when "Added tests" is not marked
            exit 1
          fi
