name: Pull Request Checklist

on:
  issue_comment:
    types:
      - created
  pull_request:
    types:
      - synchronize

jobs:
  checklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check Checklist
        id: check
        run: |
          issue_number=$(echo "${{ github.event.comment.body }}" | grep -oP '(\d+)')
          issue_data=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/${issue_number}")
          checklist=$(echo "${issue_data}" | jq -r '.body' | grep -oP '\- \[.\] .+' | sed 's/\- \[.\] //g')

          # Check if "Added tests" is marked
          if echo "${checklist}" | grep -q "\[x\] added tests"; then
            echo "The 'Added tests' checkbox is marked."
            echo "::set-output name=checkbox_marked::true"
          else
            echo "The 'Added tests' checkbox is not marked."
            echo "::set-output name=checkbox_marked::false"
          fi

      - name: Trigger Actions
        if: success() && steps.check.outputs.checkbox_marked == 'true'
        # Add your actions here
