name: check label

on:
  pull_request:
    types: [ labeled ]


jobs:
  build:
    if: ${{ github.event.label.name == 'deploy_dev' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
